# Antigen
source $(brew --prefix)/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen bundle Valiev/almostontop
antigen bundle djui/alias-tips

antigen apply

# ZSH
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="bullet-train"

plugins=(git virtualenvwrapper brew extract)
plugins+=(osx node npm python)
plugins+=(alias-tips zsh-completions almostontop zsh-autosuggestions)
plugins+=(zsh-syntax-highlighting)

COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
DEFAULT_USER="thulioph"

source $ZSH/oh-my-zsh.sh

# ALIAS

## Git
alias gcm="git commit -m"
alias gst="git status"
alias gps="git push"
alias gpl="git pull"
alias gcmedit="git commit --amend -m"
alias glog="git log --graph --decorate --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

## OSX
# alias ~="cd ~"
# alias la="ls -a"
alias emulator="open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/"
alias ip="ifconfig"
alias wk='workon'
alias pserver="python -m SimpleHTTPServer"

## NPM
npm set init.author.email "thulioph@gmail.com"
npm set init.author.name "Thulio Philipe"
npm set init.license "MIT"

# Show how much RAM application uses
# https://github.com/paulmillr/dotfiles
# $ ram safari
function ram() {
  local sum
  local items
  local app="$1"
  if [ -z "$app" ]; then
    echo "First argument - pattern to grep from processes"
  else
    sum=0
    for i in `ps aux | grep -i "$app" | grep -v "grep" | awk '{print $6}'`; do
      sum=$(($i + $sum))
    done
    sum=$(echo "scale=2; $sum / 1024.0" | bc)
    if [[ $sum != "0" ]]; then
      echo "${fg[blue]}${app}${reset_color} uses ${fg[green]}${sum}${reset_color} MBs of RAM."
    else
      echo "There are no processes with pattern '${fg[blue]}${app}${reset_color}' are running."
    fi
  fi
}

# Editor
export EDITOR="subl -n -w"

# Virtualenv
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Language Environment
export LANG=en_US.UTF-8

# SSH
export SSH_KEY_PATH="~/.ssh/dsa_id"