#!/usr/bin/env bash

e_header "Installing Keynote"
mas install keynote
e_success "Keynote installed"

e_header "Installing Monosnap"
mas install 540348655
e_success "Monosnap installed"

e_header "Installing Theine"
mas install 955848755
e_success "Theine installed"