#!/usr/bin/env bash

e_header "Creating SSH"
ssh-keygen -t rsa -b 4096 -C $USER_EMAIL
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
e_success "SSH created"

e_header "Installing GIT"
brew install git
e_success "GIT installed"

e_header "Installing NODE"
brew install node
e_success "Node installed"

e_header "Installing NVM"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
e_success "NVM installed"

e_header "Installing PYTHON3"
brew install python3
e_success "Python3 installed"

e_header "Installing PIP"
easy_install pip
e_success "Pip installed"

e_header "Updating PIP"
pip install --upgrade pip
e_success "Pip Updated"

e_header "Installing SASS"
gem install sass
e_success "SASS installed"

e_header "Installing Showterm"
gem install showterm
e_success "Showterm installed"

e_header "Installing Heroku Toolbet"
brew install heroku/brew/heroku
e_success "Heroku Toolbet installed"

e_header "Installing NGROK"
brew cask install ngrok
e_success "NGROK installed"

e_header "Installing Terminal Helpers"
brew install wget curl tree wifi-password coreutils
e_success "Terminal Helpers installed"

e_header "Installing GPG-Suite"
brew cask install gpg-suite
e_success "GPG-Suite installed"

e_header "Installing iTerm2"
brew cask install iterm2
e_success "iTerm2 installed"

e_header "Installing Docker"
brew cask install docker
e_success "Docker installed"

e_header "Installing Postman"
brew cask install postman
e_success "Postman installed"

e_header "Installing VS Code"
brew cask install visual-studio-code
e_success "VS Code installed"

e_header "Installing Postgres"
brew install postgresql
e_success "Postgres installed"

e_header "Installing Quick Look Plugins"
brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlimagesize webpquicklook suspicious-package qlvideo
e_success "Quick Look Plugins installed"

e_header "Installing Antigen"
brew install antigen
e_success "Antigen installed"

e_header "Installing JSON processor"
brew install jq
e_success "JSON processor installed"

e_header "Installing Redis"
brew install redis
e_success "Redis installed"

e_header "Installing Pipenv"
brew install pipenv
e_success "Pipenv installed"
