#!/usr/bin/env bash

e_header "Installing HomeBrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
e_success "Homebrew installed"

# ZSH

if [[ $SHELL =~ zsh ]]; then
  e_success 'You already use zsh. Awesome!'
else
  e_arrow 'Changing shell to zsh'
  # Adds zsh to shells
  command -v zsh | sudo tee -a /etc/shells
  chsh -s $(which zsh)
fi

e_success "Changed to ZSH"

# OH-MY-ZSH

if [ -d "$HOME/.oh-my-zsh" ]; then
  e_already 'oh-my-zsh'
else
  e_arrow 'Installing oh-my-zsh'
  curl -L http://install.ohmyz.sh | sh > /dev/null 2>&1
fi

e_success "Oh-my-zsh Installed"