#!/usr/bin/env bash

echo "\n\n########## Installing Homebrew Cask ##########\n\n"
brew tap caskroom/cask

echo "\n\n########## Installing Apps ##########\n\n" 
brew cask install google-chrome firefox franz slack flux evernote spotify sketch zeplin harvest rescuetime

echo "\n\n########## Installing Cask-Fonts ##########\n\n"
brew tap caskroom/fonts

echo "\n\n########## Installing Fira Code ##########\n\n"
brew cask install font-fira-code

echo "\n\n########## Installing Powerline Fonts ##########\n\n"
curl -l https://raw.githubusercontent.com/powerline/fonts/master/install.sh | sh