#!/usr/bin/env bash

# SUBLIME TEXT
sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer

# GOOGLE CHROME

wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update 
sudo apt-get install google-chrome-stable


# ZSH

if [[ $SHELL =~ zsh ]]; then
  e_success 'You already use zsh. Awesome!'
else
  e_arrow 'Changing shell to zsh'
  chsh -s $(which zsh)
fi

# OH-MY-ZSH

if [ -d "$HOME/.oh-my-zsh" ]; then
  e_already 'oh-my-zsh'
else
  e_arrow 'Installing oh-my-zsh'
  curl -L http://install.ohmyz.sh | sh > /dev/null 2>&1
fi

# TERMINATOR

sudo add-apt-repository ppa:gnome-terminator
sudo apt-get update
sudo apt-get install terminator

