#!/usr/bin/env bash

e_header "Installing Homebrew Cask"
brew tap caskroom/cask
e_success "Homebrew Cask installed"

e_header "Installing Apps"
brew cask install google-chrome firefox franz slack flux evernote spotify sketch zeplin harvest rescuetime
e_success "Apps installed"

e_header "Installing Cask-Fonts"
brew tap caskroom/fonts
e_success "Cask-Fonts installed"

e_header "Installing Fira Code"
brew cask install font-fira-code
e_success "Fira Code installed"

e_header "Installing Powerline Fonts"
curl -l https://raw.githubusercontent.com/powerline/fonts/master/install.sh | sh
e_success "Powerline Fonts installed"